name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ update-data ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Update') || contains(github.event.head_commit.message, 'Fix') || contains(github.event.head_commit.message, 'feat') || contains(github.event_name, 'repository_dispatch')

    steps:
    - uses: actions/checkout@v2
    - name: Checkout data repo
      uses: actions/checkout@v2
      with:
        repository: BLHXFY-Group/BLHXFY
        path: group
    - name: Move data files
      run: cp -r group/data/ ./
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build data
      run: pnpm deploy_action
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}